apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bmfm-sm-inference-chart.fullname" . }}
  labels:
    {{- include "bmfm-sm-inference-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bmfm-sm-inference-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bmfm-sm-inference-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      # {{- with .Values.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      serviceAccountName: {{ include "bmfm-sm-inference-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-s3-sync
          image: {{ .Values.aws.image | quote }}
          command: ["/bin/sh", "-c"]
          args:
            {{- range .Values.aws.args }}
            - {{ . | quote }}
            {{- end }}
          # envFrom:
          # - secretRef:
          #     name: {{ .Values.aws.credentials | quote }}
          env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region | quote }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image:  "image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HF_HOME
              value: {{ .Values.env.HF_HOME | quote }}
            - name: MPLCONFIGDIR
              value: {{ .Values.env.MPLCONFIGDIR | quote }}
            - name: LOGGING_CONFIG_PATH
              value: {{ .Values.env.LOGGING_CONFIG_PATH | quote }}
            - name: gt4sd_local_cache_path
              value: {{ .Values.env.gt4sd_local_cache_path | quote }}
            - name: ENABLE_CACHE_RESULTS
              value: {{ .Values.env.ENABLE_CACHE_RESULTS | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
